### ISSUE TITLE
do not parse options specified after positional arguments

### ISSUE THREAD

**Issue by mx1up** [dart-lang/args#198] opened 2021-05-31 15:10 UTC
hi,

I'd like to pass options to a shell command I'm calling. i.e. if my dart program `dgit `is a frontend to git, I'd like to be able to type:
`dgit reset --hard`
where `reset` and `--hard` are positional params that should be passed to git as is. Is this possible?

I enabled allowTrailingOptions but this still tries to parse those options.

**Comment by jakemac53** [comment] 2021-06-01 14:38
You should be able to do this if you separate the options you pass by a `--`, so for instance `dgit -- reset --hard`.

**Comment by mx1up** [comment] 2021-06-01 14:58
thanks! 
as it happens, I _just_ found out about the allowAnything parser. 
would there be any functional differences between the 2 solutions (if they are the same it seems more user friendly to not need the `--`)

**Comment by jakemac53** [comment] 2021-06-01 15:19
I don't think the allowAnything parser allows any actual options to be parsed - but if you have no options/flags and just want to forward everything on that would work.

**Comment by jakemac53** [comment] 2021-06-01 15:21
I am going to go ahead and close this (the existing behavior isn't likely something we could reasonably change). It is the intended behavior that options can be provided before or after positional arguments. Whether that is the right behavior is up for debate but we can't really change it at this point.

**Closed by jakemac53** 2021-06-01 15:21 UTC

**Comment by mx1up** [comment] 2021-06-01 17:32
ok, thanks for the feedback. 
btw, I simplified the example above. in fact, it is only a subcommand that accepts these arguments to pass on, so in that case it is no problem that no other options are available to the dart command as this is handled by a parent command.
